-- Content management, hierarchical categories and scheduled publishing.
-- Run once in the Supabase SQL Editor. The script is safe to run again.

begin;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 80),
  slug text not null unique,
  parent_id bigint references public.categories(id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists categories_root_name_unique
  on public.categories (lower(name)) where parent_id is null;
create unique index if not exists categories_child_name_unique
  on public.categories (parent_id, lower(name)) where parent_id is not null;

insert into public.categories (name, slug, sort_order)
values
  ('Biblia', 'biblia', 10),
  ('Libros', 'libros', 20),
  ('Sin categoría', 'sin-categoria', 999)
on conflict (slug) do nothing;

alter table public.audios
  add column if not exists category_id bigint references public.categories(id) on delete set null,
  add column if not exists status text not null default 'published',
  add column if not exists scheduled_at timestamptz,
  add column if not exists published_at timestamptz,
  add column if not exists storage_path text,
  add column if not exists notification_sent_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'audios_status_check' and conrelid = 'public.audios'::regclass
  ) then
    alter table public.audios
      add constraint audios_status_check check (status in ('draft', 'scheduled', 'published'));
  end if;
end $$;

update public.audios
set
  status = 'published',
  published_at = coalesce(published_at, created_at),
  category_id = coalesce(category_id, (select id from public.categories where slug = 'sin-categoria')),
  updated_at = now()
where published_at is null or category_id is null;

create index if not exists audios_publication_index
  on public.audios (status, published_at desc);
create index if not exists audios_category_index
  on public.audios (category_id, published_at desc);

alter table public.categories enable row level security;
alter table public.audios enable row level security;

-- Remove legacy client-side write policies. Administrative mutations now use
-- the admin-content Edge Function with the service role.
do $$
declare policy_record record;
begin
  for policy_record in
    select policyname from pg_policies where schemaname = 'public' and tablename = 'audios'
  loop
    execute format('drop policy if exists %I on public.audios', policy_record.policyname);
  end loop;
end $$;

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories"
  on public.categories for select to anon, authenticated using (true);

create policy "Public can read published audios"
  on public.audios for select to anon, authenticated
  using (status = 'published' and published_at is not null and published_at <= now());

grant select on public.categories to anon, authenticated;
grant select on public.audios to anon, authenticated;
revoke insert, update, delete on public.categories from anon, authenticated;
revoke insert, update, delete on public.audios from anon, authenticated;

-- Publish due content every minute. Updating scheduled -> published is what
-- triggers the notification webhook.
create extension if not exists pg_cron with schema pg_catalog;

do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'publish-scheduled-audios';
  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
end $$;

select cron.schedule(
  'publish-scheduled-audios',
  '* * * * *',
  $cron$
    update public.audios
    set status = 'published',
        published_at = scheduled_at,
        updated_at = now()
    where status = 'scheduled'
      and scheduled_at is not null
      and scheduled_at <= now();
  $cron$
);

commit;
