-- Shared journey counter and current community announcement.
-- Run once in the Supabase SQL Editor.

begin;

create table if not exists public.journey_settings (
  id smallint primary key check (id = 1),
  started_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.journey_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.community_announcements (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(trim(message)) between 1 and 500),
  is_current boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists community_announcements_one_current
  on public.community_announcements (is_current)
  where is_current = true;

alter table public.journey_settings enable row level security;
alter table public.community_announcements enable row level security;

drop policy if exists "Public can read journey settings" on public.journey_settings;
create policy "Public can read journey settings"
  on public.journey_settings for select to anon, authenticated using (true);

drop policy if exists "Public can read current announcement" on public.community_announcements;
create policy "Public can read current announcement"
  on public.community_announcements for select to anon, authenticated using (is_current = true);

grant select on public.journey_settings to anon, authenticated;
grant select on public.community_announcements to anon, authenticated;
revoke insert, update, delete on public.journey_settings from anon, authenticated;
revoke insert, update, delete on public.community_announcements from anon, authenticated;

commit;
